export type User = {
  id: string;
  fullname: string;
  street1: string;
  street2: string;
  city: string;
  state: string;
  zip: string;
  phone: string;
  email: string;
  username: string;
  servicecategory: string | null;
  isadmin: boolean;
  issp: boolean;
  iscustomer: boolean;
  address: string;
  qualifications: string | null;
  providername: string | null;
  isactive: boolean;
};
